### ISSUE TITLE
Inconsistant pot entry order across systems

### ISSUE THREAD

**Issue by pschichtel** [CubeEngine/messageextractor#24]
Possibly a locale issue in the ordering

**Comment by boeserwolf91** [comment]
@pschichtel I cannot reproduce the issue. Like I read the order of String.compareTo isn't related to the defined Locale. To compare strings due to the locale one needs a [Collator](http://docs.oracle.com/javase/7/docs/api/java/text/Collator.html) instance. I definitely do not use this class. 

[An example of both behaviors can be found here](http://www.javapractices.com/topic/TopicAction.do?Id=207)

**Comment by boeserwolf91** [comment]
Can you show me the output from the two systems please?

**Comment by pschichtel** [comment]
I have no example available and it was a really weird case, maybe it was only a strange behavior of the diff viewer
